
package view;

import controller.Persist;
import controller.ServicoController;
import model.PropostaModel;

/**
 * Classe responsável pelo manejamento do forms de serviço
 * @author lucas
 */
public class ServicoFrame extends javax.swing.JFrame {

    private ServicoController servicoController;
    
    /**
     * Creates new form EmpresaFrame
     */
    public ServicoFrame() {
        initComponents();
    }
    
    /**
     * Construtor
     * @param sc informações do serviço
     */
    public ServicoFrame(ServicoController sc){
        initComponents();
        //Carrega campos com informações passadas
        categoriasLabel.setText(sc.getCategorias());
        descricaoTextArea.setText(sc.getDescricao());
        entregaLabel.setText(sc.getEntrega());
        valorLabel.setText(String.valueOf(sc.getValor()));
        transporteCheckBox.setSelected(sc.isTransporte());
        presencaCheckBox.setSelected(sc.isPresenca());
        tituloLabel.setText(sc.getServico());
        lblCidade.setText(sc.getCidade());
        lblEstado.setText(sc.getEstado());
        servicoController = sc;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        categoriasLabel = new javax.swing.JLabel();
        entregaLabel = new javax.swing.JLabel();
        presencaCheckBox = new javax.swing.JCheckBox();
        transporteCheckBox = new javax.swing.JCheckBox();
        descricaoScrollPane = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        contatarButton = new javax.swing.JButton();
        btnOferecer = new javax.swing.JButton();
        lblDescricao = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(800, 600));

        tituloLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        tituloLabel.setText("Empresa 1: Sistema de recomendação");

        valorLabel.setText("Valor: R$ 8.260,00");

        categoriasLabel.setText("Categorias: Computação, Desenvolvimento Web, Sistemas de recomendação");

        entregaLabel.setText("Entrega: 30/11/2019");

        presencaCheckBox.setText("Presença");
        presencaCheckBox.setEnabled(false);

        transporteCheckBox.setText("Transporte");
        transporteCheckBox.setEnabled(false);

        descricaoTextArea.setEditable(false);
        descricaoTextArea.setColumns(20);
        descricaoTextArea.setRows(5);
        descricaoScrollPane.setViewportView(descricaoTextArea);

        contatarButton.setText("Contatar empresa");

        btnOferecer.setText("Ofrecer Serviço");
        btnOferecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOferecerActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        lblEstado.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(contatarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOferecer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valorLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(categoriasLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(entregaLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCidade)
                                        .addGap(93, 93, 93)
                                        .addComponent(lblEstado)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(transporteCheckBox))
                                    .addComponent(presencaCheckBox))))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorLabel)
                    .addComponent(categoriasLabel)
                    .addComponent(presencaCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entregaLabel)
                    .addComponent(transporteCheckBox)
                    .addComponent(lblCidade)
                    .addComponent(lblEstado))
                .addGap(18, 18, 18)
                .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOferecer)
                    .addComponent(contatarButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOferecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOferecerActionPerformed
        //Registra nova proposta
        PropostaModel pm = new PropostaModel();
        pm.enviarProposta(servicoController);
    }//GEN-LAST:event_btnOferecerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpresaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOferecer;
    private javax.swing.JLabel categoriasLabel;
    private javax.swing.JButton contatarButton;
    private javax.swing.JScrollPane descricaoScrollPane;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JLabel entregaLabel;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JCheckBox presencaCheckBox;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JCheckBox transporteCheckBox;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables

    private int id;
    private String nome;
    private int areaDeAtuacaoId;
    private String descricao;
    private EmpresaFrame empresa;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getAreaDeAtuacaoId() {
        return areaDeAtuacaoId;
    }

    public void setAreaDeAtuacaoId(int areaDeAtuacaoId) {
        this.areaDeAtuacaoId = areaDeAtuacaoId;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    public EmpresaFrame getEmpresa() {
        return empresa;
    }

    public void setEmpresa(EmpresaFrame empresa) {
        this.empresa = empresa;
    }
    
    public void setEmpresa(int empresaId) {
    }
}
